/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.awt.CardLayout;

/**
 *
 * @author ariff
 */
public class AplikasiPenampilGambardenganComboBox extends javax.swing.JFrame {

    /**
     * Creates new form AplikasiPenampilGambardenganButton
     */
    public AplikasiPenampilGambardenganComboBox() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        btnpanel = new javax.swing.JPanel();
        lblpilihgambar = new javax.swing.JLabel();
        Cbpilih = new javax.swing.JComboBox<>();
        imagePanel = new javax.swing.JPanel();
        lblglass = new javax.swing.JLabel();
        lbljava = new javax.swing.JLabel();
        lblpost = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblpilihgambar.setText("Pilih Gambar");
        btnpanel.add(lblpilihgambar);

        Cbpilih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Glasfish", "Java EE", "PostgreSQL" }));
        Cbpilih.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbpilihActionPerformed(evt);
            }
        });
        btnpanel.add(Cbpilih);

        getContentPane().add(btnpanel, java.awt.BorderLayout.PAGE_START);

        imagePanel.setLayout(new java.awt.CardLayout());

        lblglass.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblglass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/glass.jpg"))); // NOI18N
        lblglass.setMaximumSize(new java.awt.Dimension(316, 400));
        lblglass.setMinimumSize(new java.awt.Dimension(316, 400));
        lblglass.setPreferredSize(new java.awt.Dimension(316, 400));
        imagePanel.add(lblglass, "0");

        lbljava.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbljava.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/javaee.jpeg"))); // NOI18N
        imagePanel.add(lbljava, "1");

        lblpost.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpost.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/post.jpg"))); // NOI18N
        lblpost.setText("jLabel1");
        imagePanel.add(lblpost, "2");

        getContentPane().add(imagePanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbpilihActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbpilihActionPerformed
        CardLayout cl = (CardLayout)(pCardLayout.getLayout());
        cl.show(pCardLayout, String.valueOfgetSelectedIndex())
    }//GEN-LAST:event_CbpilihActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambardenganComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambardenganComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambardenganComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiPenampilGambardenganComboBox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiPenampilGambardenganComboBox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cbpilih;
    private javax.swing.JPanel btnpanel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblglass;
    private javax.swing.JLabel lbljava;
    private javax.swing.JLabel lblpilihgambar;
    private javax.swing.JLabel lblpost;
    // End of variables declaration//GEN-END:variables
    // End of variables declaration                   
    // End of variables declaration                   
}

}gvtyjp7